version: '3.3'

services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: react-app-container
        ports:
            - '3000:3000'
        volumes:
            - .:/app
            - /app/node_modules
            - ./data:/app/data
            - ./.env:/app/.env
        env_file:
            - .env
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: npm start
        networks:
            custom_network:
                ipv4_address: 172.20.0.10 # <-- Đặt IP cố định ở đây

networks:
    custom_network:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/24 # <-- Phạm vi IP pool bạn đặt
