version: '3.8'

services:
    react-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: react-app-container
        ports:
            - '3000:3000'
        volumes:
            - .:/app # Mount source code
            - /app/node_modules # Mount node_modules
            - ./data:/app/data # Mount thư mục data
            - ./.env:/app/.env # Mount file .env vật lý (nếu app cần đọc file)
        env_file:
            - .env # Load biến môi trường từ file .env
        environment:
            - CHOKIDAR_USEPOLLING=true # Thêm biến ngoài file .env nếu cần
        command: npm start
        networks:
            - custom_network

networks:
    custom_network:
        driver: bridge
